---
title: "In Class Assignment Module 7"
author: "Arturo Ortiz"
date: "2023-11-29"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r}

d1 <- cbind(rep(1, 50), rnorm(50, 4, 1), rnorm(50, 8, 1))
d2 <- cbind(rep(2, 50), rnorm(50, 8, 1), rnorm(50, 0, 1))
d3 <- cbind(rep(3, 50), rnorm(50, 0, 1), rnorm(50, 0, 1))

mydata1 <- rbind(d1, d2, d3)
mydata1 <- data.frame(mydata1)
colnames(mydata1) <- c("True.Cluster", "x", "y")

mydata1_dist <- dist(mydata1)
mydata1_hclust <- hclust(mydata1_dist, method = "single")
mydata1_cutree <- cutree(mydata1_hclust, 3)
plot(mydata1, col = mydata1_cutree)
```

```{r}

d1 <- cbind(rep(1, 50), rnorm(50, 4, 3), rnorm(50, 8, 3))
d2 <- cbind(rep(2, 50), rnorm(50, 8, 3), rnorm(50, 0, 3))
d3 <- cbind(rep(3, 50), rnorm(50, 0, 3), rnorm(50, 0, 3))

mydata2 <- rbind(d1, d2, d3)
mydata2 <- data.frame(mydata2)
colnames(mydata2) <- c("True.Cluster2", "x", "y")
plot(mydata2, col = mydata2$True.Cluster2)
```


```{r}
mydata2_dist <- dist(mydata2)
mydata2_hclust <- hclust(mydata2_dist, method = "average")
mydata2_cutree <- cutree(mydata2_hclust, 3)
plot(mydata2, col = mydata2_cutree, main = "Average")
```

```{r}
mydata2_hclust1 <- hclust(mydata2_dist, method = "single")
mydata2_cutree1 <- cutree(mydata2_hclust1, 3)
plot(mydata2, col = mydata2_cutree1, main = "Single")
```

```{r}
mydata2_hclust3 <- hclust(mydata2_dist, method = "complete")
mydata2_cutree3 <- cutree(mydata2_hclust3, 3)
plot(mydata2, col = mydata2_cutree3, main = "Complete")
```

```{r}
mydata2_kmeans <- kmeans(mydata2, centers = 3)
plot(mydata2, col = mydata2_kmeans$cluster, main = "K-means")
```

Because hierarchical clustering shows a higher degree of agreement between the clusters it produces, it performs better compared to K-means.  Because hierarchical clustering successfully clusters a greater proportion of data points, it performs better in this situation, as indicated by the higher diagonal values."


